# Generated by Django 2.0.2 on 2018-09-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Regi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Match_Name', models.CharField(max_length=50)),
                ('First_Team_Name', models.CharField(max_length=50)),
                ('Second_Team_Name', models.CharField(max_length=50)),
                ('Team1_Player1', models.CharField(max_length=50)),
                ('Team1_Player2', models.CharField(max_length=50)),
                ('Team1_Player3', models.CharField(max_length=50)),
                ('Team1_Player4', models.CharField(max_length=50)),
                ('Team1_Player5', models.CharField(max_length=50)),
                ('Team1_Player6', models.CharField(max_length=50)),
                ('Team1_Player7', models.CharField(max_length=50)),
                ('Team1_Player8', models.CharField(max_length=50)),
                ('Team1_Player9', models.CharField(max_length=50)),
                ('Team1_Player10', models.CharField(max_length=50)),
                ('Team1_Player11', models.CharField(max_length=50)),
                ('Team2_Player1', models.CharField(max_length=50)),
                ('Team2_Player2', models.CharField(max_length=50)),
                ('Team2_Player3', models.CharField(max_length=50)),
                ('Team2_Player4', models.CharField(max_length=50)),
                ('Team2_Player5', models.CharField(max_length=50)),
                ('Team2_Player6', models.CharField(max_length=50)),
                ('Team2_Player7', models.CharField(max_length=50)),
                ('Team2_Player8', models.CharField(max_length=50)),
                ('Team2_Player9', models.CharField(max_length=50)),
                ('Team2_Player10', models.CharField(max_length=50)),
                ('Team2_Player11', models.CharField(max_length=50)),
                ('Over', models.IntegerField()),
            ],
        ),
    ]
