# Generated by Django 2.0.2 on 2018-09-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Go_Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='match_regi',
            name='Match_Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='match_regi',
            name='Over',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='go_live',
            name='name',
            field=models.ForeignKey(on_delete=None, to='cricket.Match_Regi', to_field='Over'),
        ),
        migrations.AddField(
            model_name='go_live',
            name='name2',
            field=models.ForeignKey(on_delete=None, related_name='Joy', to='cricket.Match_Regi', to_field='Match_Name'),
        ),
    ]
