# Generated by Django 2.0.2 on 2018-09-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_auto_20180920_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='go_live',
            name='name2',
        ),
        migrations.AlterField(
            model_name='go_live',
            name='name',
            field=models.ForeignKey(on_delete=None, to='cricket.Match_Regi', to_field='First_Team_Name'),
        ),
        migrations.AlterField(
            model_name='match_regi',
            name='First_Team_Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='match_regi',
            name='Match_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='match_regi',
            name='Second_Team_Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
