# Generated by Django 2.0.2 on 2018-09-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0004_auto_20180920_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Go_Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=None, to='cricket.Match_Regi', to_field='First_Team_Name')),
            ],
        ),
    ]
