# Generated by Django 2.0.2 on 2018-09-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0005_go_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_regi',
            name='Bat_First',
            field=models.CharField(choices=[('a', 'Team 1'), ('b', 'Team 2')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='match_regi',
            name='Match_Name',
            field=models.CharField(choices=[('a', 'ODI'), ('b', 'Test'), ('c', 'T20')], default='a', max_length=1),
        ),
    ]
